Users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from Users.apps import UsersConfig
from Users.views import CustomLoginView, UserEditProfileView, UserCreateProfileView, MyPasswordChangeView, \
    user_activation, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserEditProfileView.as_view(), name='profile'),
    path('register/', UserCreateProfileView.as_view(), name='register'),
    path('password/', MyPasswordChangeView.as_view(), name='change_passwd'),
    path('activate/<str:token>/', user_activation, name='activate'),
    path('reset_password/', reset_password, name='reset_password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('users/', include('Users.urls', namespace='users')),
]

Users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(
        verbose_name='почта',
        unique=True
    )

    number = models.CharField(max_length=25, verbose_name='номер телефона')
    avatar = models.ImageField(verbose_name='аватар', upload_to='users/')
    country = models.CharField(max_length=35, verbose_name='страна')
    token = models.CharField(max_length=250, verbose_name='токен')
    token_created = models.DateTimeField(null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

Users/forms.py
from django.contrib.auth.forms import UserChangeForm, PasswordResetForm
from django import forms

from Users.models import User


class CustomEditUserForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar')


class NewCustomEditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class CustomPasswordResetForm(PasswordResetForm):
    pass

Users/views.py
import datetime
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView
from Users.forms import CustomEditUserForm, NewCustomEditUserForm, CustomPasswordResetForm
from Users.models import User
from config import settings


class CustomLoginView(LoginView):
    template_name = 'users/login.html'


class UserCreateProfileView(CreateView):
    model = User
    form_class = NewCustomEditUserForm
    template_name = 'users/user_create.html'
    success_url = '/'

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            ###
            self.object.token = make_password(self.object.password).replace('/', '')
            self.object.token_created = datetime.datetime.now().astimezone()
            self.object.is_active = False
            ###
            self.object.set_password(form.data.get('password'))
            self.object.save()
            ###
            send_mail(
                subject='Активация',
                message=f'http://localhost:8000/users/activate/{self.object.token}/',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email],

            )
        return super().form_valid(form)


class UserEditProfileView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = CustomEditUserForm
    success_url = reverse_lazy('prod:product')

    def get_object(self, queryset=None):
        return self.request.user


class MyPasswordChangeView(PasswordChangeView):
    success_url = '/'
    template_name = 'users/change_passwd.html'


def user_activation(request, token):
    u = User.objects.filter(token=token).first()
    if u:
        u.is_active = True
        u.save()
    return redirect('http://localhost:8000')


def reset_password(request):
    if request.method == 'POST':

        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            mail = password_reset_form.cleaned_data['email']

            try:
                user = User.objects.get(email=mail)

            except Exception:
                user = False

            if user:
                new_password = secrets.token_urlsafe(18)[:15]
                user.set_password(new_password)
                user.save()
                send_mail(
                    subject='Смена пароля',
                    message=f'Пароль успешно обновлен, для входа в аккаун используйте следующие дынные:\nПочта: {mail}\nПароль: {new_password}',
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[mail],
                    fail_silently=False
                )
                return redirect('users:login')

    return render(request, 'users/password_recovery.html')

Users/templates/users/change_passwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Смена пароля</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сменить пароль</button>
</form>
</body>
</html>

Users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Логин</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
    <a class="btn btn-outline-info" href="{% url 'users:reset_password' %}">Забыли пароль?</a>
</form>
</body>
</html>

Users/templates/users/password_recovery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Логин</title>
</head>
<body>
<div class="container">
    <h1>Забыли пароль?</h1>
    <p>Введите e-mail адрес и мы отправим новый пароль.</p>
    <form method="post" class="email-form">
        {% csrf_token %}
        <input type="email" name="email" autocomplete="email" class="form-control">
        <br>
        <button type="submit" class="p-2 btn btn-outline-dark">Отправить</button>

    </form>
</div>
</body>
</html>

Users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
</body>
</html>

Users/templates/users/user_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
</body>
</html>

Users/templates/users/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
</body>
</html>