Users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from Users.apps import UsersConfig
from Users.views import CustomLoginView, UserEditProfileView, UserCreateProfileView, MyPasswordChangeView, \
    user_activation, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserEditProfileView.as_view(), name='profile'),
    path('register/', UserCreateProfileView.as_view(), name='register'),
    path('password/', MyPasswordChangeView.as_view(), name='change_passwd'),
    path('activate/<str:token>/', user_activation, name='activate'),
    path('reset_password/', reset_password, name='reset_password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('users/', include('Users.urls', namespace='users')),
]

products/urls.py
from django.urls import path
from products.apps import ProductsConfig
from products.views import *

app_name = ProductsConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('category_create/', CategoryCreateView.as_view(), name='category_create'),
]

products/models.py
from django.db import models


class Product(models.Model):
    STATUS_TRUE = 'True'
    STATUS_FALSE = 'False'
    STATUSES = (
        (STATUS_TRUE, 'Активна'),
        (STATUS_FALSE, 'Неактивна'),
    )
    name = models.CharField(max_length=250, verbose_name='Наименование продукта')
    price = models.IntegerField(verbose_name='Цена продукта')
    description = models.TextField(verbose_name='Описание')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    owner = models.ForeignKey('Users.User', on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, max_length=10, default=STATUS_FALSE, verbose_name='Признак публикации')

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return f'{self.name} {self.category} {self.price} {self.description}'


class Version(models.Model):
    STATUS_ACTIVE = 'active'
    STATUS_INACTIVE = 'inactive'
    STATUSES = (
        (STATUS_ACTIVE, 'активна'),
        (STATUS_INACTIVE, 'неактивна'),
    )

    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    version_number = models.IntegerField(verbose_name='Номер версии')
    version_name = models.CharField(max_length=250, verbose_name='Имя версии')
    version_status = models.CharField(choices=STATUSES, default=STATUS_INACTIVE, max_length=10, verbose_name='Статус')

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def __str__(self):
        return f'{self.version_number} {self.version_name} {self.version_status}'


class Category(models.Model):
    category_name = models.CharField(max_length=200, verbose_name='Название категории')

products/forms.py
from django import forms
from products.models import Product, Version


class ProductForm(forms.ModelForm):
    black_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_name(self):

        name = self.cleaned_data['name']
        if name in self.black_list:
            raise forms.ValidationError('Содержит запрещенное слово в названии')
        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        if description in self.black_list:
            raise forms.ValidationError('Содержит запрещенное слово в описании')
        return description


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

products/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db import transaction
from django.forms import inlineformset_factory
from django.shortcuts import render

from products.forms import ProductForm, VersionForm
from products.models import Product, Version, Category
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from products.services import cache_categories


class ProductListView(ListView):
    model = Product


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('products:product_list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(ProductCreateView, self).form_valid(form)


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('products:product_list')

    def test_func(self):
        product = self.get_object()
        return self.request.user.has_perm('moderator') or product.owner == self.request.user


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('products:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        FormSet = inlineformset_factory(self.model, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = FormSet(self.request.POST, instance=self.object)
        else:
            formset = FormSet(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            if form.is_valid():
                self.object = form.save()  # Student
                if formset.is_valid():
                    formset.instance = self.object
                    formset.save()  # Subject

        return super().form_valid(form)

    def test_func(self):
        product = self.get_object()
        return self.request.user.has_perm('moderator') or product.owner == self.request.user


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['cache_categories'] = cache_categories()
        return context_data


class CategoryCreateView(CreateView):
    model = Category
    fields = '__all__'
    success_url = reverse_lazy('products:category_list')

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'products/includes/inc_main_menu.html' %}
<head>
    <meta charset="UTF-8">
    <title>Продукты</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
{% if user.is_authenticated %}
<body>
{% block content %}
{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
{% else %}
<div class="col-8">Чтобы пользоваться сайтом, вам необходимо авторизоваться.</div>
{% endif %}
</html>

products/templates/products/category_form.html
{% extends 'products/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/category_list.html
{% extends 'products/base.html' %}
{% block content %}
<div class="container">
    <table class="table table-hover border-dark"> {# table-success #}
        <thead>
        <tr>
            <td>Название категории</td>
        </tr>
        </thead>
        <tbody>
        {% for category in cache_categories %}
        <tr>
            <td>{{ category.category_name|title }}</td>
            <td>
                {% for product in category.product_set.all %}
                {{ product.product_name|title }}<br>
                {% endfor %}
            </td>
            {% endfor %}
        </tbody>
    </table>
</div>
<script src="/static/js/bootstrap.bundle.js"></script>
{% endblock %}

products/templates/products/product_confirm_delete.html
{% extends 'products/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p><h5> Вы действительно хотите удалить продукт {{object.name}}? </h5></p>
                <a class="p-2 btn btn-primary"
                   href="{% url 'products:product_list' %}">Отменить</a>
                <button class="p-2 btn btn-danger" type="submit">Удалить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/product_form.html
{% extends 'products/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/product_list.html
{% extends 'products/base.html' %}
{% block content %}
<div class="container">
    <table class="table caption-top">
        <caption>Продукты</caption>
        <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Цена</th>
            <th scope="col">Описание</th>
            <th scope="col">Категория</th>
            <th scope="col">Создатель</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{object.name}}</td>
            <td>{{object.price}}</td>
            <td>{{object.description}}</td>
            <td>{{object.category}}</td>
            <td>{{object.owner}}</td>
            <td>
                <a class="p-1 btn btn-primary" href="{% url 'products:product_update' object.pk %}">Редактировать</a>
                <a class="p-1 btn btn-danger" href="{% url 'products:product_delete' object.pk %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}